add markdown keyboard toolbar
qeude/SwiftDown pull request #30
Opened 2024-01-20 03:41 UTC by rossbrandon

## Description

Adds a keyboard toolbar to support easy insertion of markdown syntax.

### Supported buttons:
- Headings: H1, H2, and H3
- Bold text
- Italicized text
- Unordered lists
- Ordered lists
- Blockquotes
- Links
- Code blocks

### Changes:
- Create `MarkdownKeyboardToolbar` - `SwiftDownEditor` extension to attach a keyboard toolbar to the `UITextView`
- Add `hasKeyboardToolbar` modifier to `SwiftDownEditor`. The keyboard is enabled by default but can be disabled with the `.hasKeyboardToolbar(false)` modifier.
- Initialize keyboard toolbar within `SwiftDown` if `hasKeyboardToolbar` is enabled. 

## Example

### Screenshot:

<img width="430" alt="keyboard_toolbar_screenshot" src="https://github.com/qeude/SwiftDown/assets/31011626/38286e70-b691-4c84-b640-3de78b756f56">

### Screencast:

![keyboard_demo](https://github.com/qeude/SwiftDown/assets/31011626/809588a3-5fb3-4aed-b7ad-a46314849dad)

2024-01-23 20:01 UTC, qeude requested changes
👋 Hi!
Thanks for your contribution, this is an awesome addition to this package, I'm so glad that people like you contribute to this package!
I've made some feedback, but no big deal, this is mostly related to the structure
Don't hesitate if it's not clear or if you want me to tackle these feedback 🙏

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  }
I think we could use polymorphism here by having two methods with the same name like
- `keyboardButton(title: String, action: Selector) -> UIBarButtonItem`
- `keyboardButton(icon: String, action: Selector) -> UIBarButtonItem`
WDYT?

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +    return UIBarButtonItem(
`return` is not needed here

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +    return UIBarButtonItem(
`return` is not needed here

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +/// - Code Blocks
I know it's a debate in the dev community, but I like to keep comments for very technical/not easily understandable parts. I feel like in that case it just rephrases the following code and doesn't bring additional information. WDYT on removing this?

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Moves the cursor position after the inserted characters
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Moves the cursor position after the inserted characters
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Moves the cursor position after the inserted characters
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Moves the cursor to the end of the selected text, if applicable
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Moves the cursor to the end of the selected text, if applicable
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Adds 1 trailing whitespace at the current cursor position
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Adds 1 trailing whitespace at the current cursor position1
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Adds 1 trailing whitespace at the current cursor position
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Move cursor by the given offset
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Validate if the selected text range contains a link
Same comment about comments

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +}
```suggestion
  var containsLink: Bool {
    guard let selectedTextRange = self.selectedTextRange,
      let selectedText = self.text(in: selectedTextRange) else {
      return false
    }
    do {
      let detector = try NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue)
      let matches = detector.matches(
        in: selectedText, options: [],
        range: NSRange(location: 0, length: selectedText.utf16.count)
      )
      return !matches.isEmpty
    } catch {
      return false
    }
  }
}
```

2024-01-23 20:01 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +    let selectedEnd = self.selectedEnd
Is there a reason to use a locale variable instead of directly using both `self.selectedStart` and `self.selectedEnd` instead? (this question applies for all actions above

2024-01-23 20:35 UTC, rossbrandon commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +/// - Code Blocks
That's fair. I can clean these up.

2024-01-23 20:36 UTC, rossbrandon commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Moves the cursor position after the inserted characters
Commenting here once, but applies to all of these methods. The reason that I chose to make an explicit comment here was due to the `moveCursor` function. I felt that the behavior of moving the cursor `x` amount of spaces was not immediately clear so I clarified exactly what was happening. 
If you feel that these are not necessary, I can remove them. Up to you :)

2024-01-23 20:37 UTC, rossbrandon commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +    let selectedEnd = self.selectedEnd
I added these if the method used these variables more than once. This is so that the offset did not have to be computed more than once.

2024-01-23 20:38 UTC, rossbrandon commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  }
👍 That makes sense - I will make the change.

2024-01-24 08:41 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Moves the cursor position after the inserted characters
I see now 😁 Well, I think we could just keep this part of the comment what do you think?

2024-01-24 08:43 UTC, qeude commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +    let selectedEnd = self.selectedEnd
It makes sense, didn't remember about the being computed properties 🙏

2024-01-24 18:37 UTC, rossbrandon commented on Sources/SwiftDown/MarkdownKeyboardToolbar.swift
> +  /// Moves the cursor position after the inserted characters
Done

2024-01-28 20:02 UTC, qeude requested changes
Thanks for your changes, and for doing these so quickly ⚡
I just found out a weird behavior on smallest iPhone screens such as the iPhone SE 1st gen here
<img width="506" alt="image" src="https://github.com/qeude/SwiftDown/assets/19294297/f7d38b16-dcc0-40c0-a8ff-50f97c61be6f">
I think the "best" fix would be to make the view scrollable, but if you prefer to just resize views, I would be ok to do so since there won't be any smaller screen size cases. If we have more button in the future, we would have to go for a scrollable view anyway.

2024-01-30 17:58 UTC, rossbrandon commented
Good catch... I added a scroll view to the UIToolbar. One weird thing I noticed is that the backgrounds of the UIToolbar and the ScrollView do not match (noticeable in dark mode on larger screens). I tried a bunch of color/transparency/etc combinations but I could not get them to be the same. Do you have any suggestions to reconcile this? I will admit that I am not very experienced with UIKit :) 

![Screenshot 2024-01-30 at 11 50 47 AM](https://github.com/qeude/SwiftDown/assets/31011626/358c9583-d7d7-4bf2-93ec-84cd530a3ebe)

![Screenshot 2024-01-30 at 11 49 04 AM](https://github.com/qeude/SwiftDown/assets/31011626/91188638-5cc6-4c8f-b172-affda8fc6226)

2024-01-31 18:20 UTC, qeude commented
@rossbrandon Well, I'm not an expert of using `UIToolbar` in an `InputAccesoryView` (which are always a nightmare to use though) but I think that we could start with something like this.
```swift
  func addKeyboardToolbar() {
    let toolbar = UIToolbar()
    toolbar.barStyle = UIBarStyle.default
    toolbar.isTranslucent = true
    toolbar.barTintColor = UIColor.systemBackground
    let h1Button = keyboardButton(title: "H1", action: #selector(self.h1Action))
    let h2Button = keyboardButton(title: "H2", action: #selector(self.h2Action))
    let h3Button = keyboardButton(title: "H3", action: #selector(self.h3Action))
    let boldButton = keyboardButton(icon: "bold", action: #selector(self.boldAction))
    let italicizeButton = keyboardButton(icon: "italic", action: #selector(self.italicizeAction))
    let unorderedListButton = keyboardButton(icon: "list.bullet",action: #selector(self.unorderedListAction))
    let orderedListButton = keyboardButton(icon: "list.number",action: #selector(self.orderedListAction))
    let blockQuoteButton = keyboardButton(icon: "quote.closing",action: #selector(self.blockQuoteAction))
    let linkButton = keyboardButton(icon: "link", action: #selector(self.linkAction))
    let codeBlockButton = keyboardButton(icon: "curlybraces", action: #selector(self.codeBlockAction))
    toolbar.setItems(
      [
        h1Button,
        h2Button,
        h3Button,
        boldButton,
        italicizeButton,
        unorderedListButton,
        orderedListButton,
        blockQuoteButton,
        linkButton,
        codeBlockButton
      ],
      animated: false
    )
    toolbar.isUserInteractionEnabled = true
    toolbar.sizeToFit()
    toolbar.isTranslucent = true
    toolbar.setBackgroundImage(UIImage(), forToolbarPosition: .any, barMetrics: .default)
    toolbar.backgroundColor = UIColor.secondarySystemBackground
    let buttonCount = CGFloat(toolbar.items?.count ?? 0)
    toolbar.frame = CGRect(x: 0, y: 0, width: max(40 * buttonCount, UIScreen.main.bounds.width), height: toolbar.frame.size.height)
    let scrollView = UIScrollView(frame:
      CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: toolbar.frame.size.height)
    )
    scrollView.showsHorizontalScrollIndicator = false
    scrollView.showsVerticalScrollIndicator = false
    scrollView.bounds = toolbar.bounds
    scrollView.contentSize = toolbar.frame.size
    scrollView.backgroundColor = UIColor.secondarySystemBackground
    scrollView.addSubview(toolbar)
    self.inputAccessoryView = scrollView
  }
```
It would also solve the color on scroll bounce WDYT?

2024-01-31 18:33 UTC, rossbrandon commented
@qeude Nice! That works great! Thanks for the help. I tested and committed the suggestion.

2024-01-31 19:04 UTC, qeude approved these changes

2024-01-31 19:04 UTC, merged